development:
  adapter: postgresql
  encoding: unicode
  database: restoran
  username: postgres
  password: 12345
  host: localhost
  pool: 5

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  username: postgres
  encording: utf8
  pool: 8
  database: new-app_production