production:
  adapter: postgresql
  username: <%= ENV["deploy_me_database_user"] %>
  password: <%= ENV["deploy_me_database_password"] %>
  pool: 8
  database: db/production.sqlite3


default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

